getkirby/kirby

branches/multilang/language.php
When setting up languages now, you can specify the reading direction (`ltr` or `rtl`) for the language:
```php
c::set('languages', array(
array(
'code'    => 'en',
'name'    => 'English',
'default' => true,
'locale'  => 'en_US',
'url'     => '/',
'direction' => 'rtl'
)
));
```
This can help you to apply the right body class in the snippet to apply the respective CSS:
```php
<body class="<?php echo $site->language()->direction() ?>">
```
=> Added support for language reading direction

branches/multilang/site.php
Right now, the `/index.php` part of the URL for `rewrite=false` setups is not being used for multi-language setups. Using the proper URL determined by SiteAbstract::__construct() solves this issue.
=> Fix #271 (rewrite=false for multi-language)

core/page.php
Return the result of the `$page->date()` as Field object.
So that it can be used with field methods, e.g. `$page->date('n')->int()`.
=> Return date() as Field

core/page.php
Enabled the use of multiple sort fields vor prev/next. More or less related to https://github.com/getkirby/panel/pull/354.
I often use a date and time field for articles. When articles are posted on the same date, and only have a differen time, this update enables the `prev` and `next` functions to return the correct previous and next article: `$article->prevVisible('date', 'asc', 'time', 'asc');`. Up till now I solved this with code in a controller but it would make more sense to be able to use the default prev/next functions.
=> prev/next sortBy on multiple fields

core/children.php
If you currently create a new page and then request the list of child pages of the parent of the new page on the same request again, the new page will be missing.
This fix adds the newly created page to the collection.
=> Add subpages to the parent collection

core/file.php
Partly fulfils #372 - example for a pretty non-sense but working custom file method:
```php
file::$methods['soshiny'] = function($file) {
return 'Everthing so shiny: <a href="' . $file->url() . '">' . $file->filename() . '</a>';
};
```
Gets called e.g. `$page->files()->first()->soshiny()`
=> Adds custom file methods, #372

core/page.php, test/PageTest.php
Calling the `page::sort` method so far resulted in hiding the page (removing the prepended number). This seems rather unintended since the core has `page::hide` for this.
Now, this change is prevented and instead `page::num` is returned when no nem `$num` is passed as parameter (also fixing an issue with sortBy calling `page::sort` as possible field, #349).
PHPunit tests have passed (I also added a new one for this) – however, we should check that the core and the panel really never use `page::sort` without a parameter to hide a page.
=> Fix `page::sort` hiding pages if called without parameter, Fix #349

kirby.php
If not template-specific controller exists, Kirby tries to use a `defaul.php` controller instead if present.
ToDo:
=> Default page controller, fix #103

core/children.php, core/pages.php, extensions/methods.php
for $pages and $children. Solves #392 .
also adds $field->toPages(',') for fields that return a string with separated uris (pass separator as parameter)
=> $pages->find for arrays

vendors/smartypants.php
SmartyPants throws a deprecated warning when using php 7, because the C++/ Java style syntax for the constructor is not supported any more.
=> Fix smartypants php7 deprecated warning

kirby.php
Use `site()->homepage()->url()` for redirect instead of `page('home')->url()`. Ran into this issue while having a custom homepage defined in `config.php` as follows:
```
c::set('home', 'projects');
```
Going to the url `/projects` gave me the following error:
```
Fatal error: Call to a member function url() on boolean in /kirby/kirby.php on line 301
```
Apparently because I’ve set a custom homepage the function `page('home')` returns nothing whereas `site()->homepage()->url()` works as expected.
=> Use `site()->homepage()->url()` for redirect

kirby/urls.php
Required for the "custom folder setup fix" for the Panel.
Also fixes a bug where the order of calling the `index` and one of `content`, `thumbs` or `assets` methods would matter.
=> Urls class: Store auto-detection flag for Panel

kirby/roots.php
Until now, the site path was the base for each of its children directories like templates, snippets etc. Only accounts and the cache could be moved elsewhere.
I think it makes sense to allow advanced users to modify the other paths as well.
=> Consider custom paths for templates, snippets etc.

branches/multilang/site.php, core/page.php, core/site.php, kirby.php, kirby/component/template.php, kirby/registry/template.php
This Happy-Birthday-Kirby-PR (\o/) is an implementation of issue #167 (different content representations using multiple templates).
This feature actually changes 60 lines of code instead of 15 I thought it would change, but it includes fallback mechanisms to choose appropriate fallback templates. I hope the code is still readable. ;)
The code implements two ways to approach the "multiple representations" problem:
1. Like in v1, you can simply add any extension to a page (like `sitemap.xml`) and it will work. It will find the sitemap page and render a totally equal result to the normal URI.
2. The more interesting approach: You can create a template `sitemap.xml.php` with custom code and it will be loaded instead of the normal one. Like I said above, the code contains a fallback to the …
=> Content representations (implements #167)

branches/multilang/language.php, kirby.php
This change (together with getkirby/toolkit#178) allows to use a different language per domain out of the box.
Example:
```php
c::set('languages', [
[
'code'    => 'en',
'name'    => 'English',
'default' => true,
'locale'  => 'en_US',
'url'     => 'https://example.com',
],
[
'code'    => 'de',
'name'    => 'Deutsch',
'locale'  => 'de_DE',
'url'     => 'https://example.de',
]
]);
```
Non-absolute language URLs like `/de`, `/` or `de` will continue to work. You can even combine them like `https://example.com/kirby` in case the languages are on a sub-folder.
---
Since this change only touches routes, it shouldn't break the Panel.
However it would make sense to add support for this in the Panel too, so that the correct language would be pre-selected per domain, that would just be an …
=> Cross-domain multilang

core/roles.php
If custom roles are defined but none as default, now there is a fallback default role `nobody` with no permissions instead of setting the `admin` role as default (prior to this commit).
=> Fix #569: fallback default role `nobody`

kirby.php
Since this part only applies to `language.detect=true` on the home page of the site, we have to add a `/` before the `?` of the added query string. 
Otherwise the if-statement part  `trim(url::current(), '/') !== rtrim($url, ‘/‘)`(from line 264) would be `true` since `url::current()` provides the url with the `/` while `$url` has not contained this `/` so far.
And this leads to an infinite redirect which this PR should fix.
=> Fix #581: prevent infinite redirect on lang detect

core/user.php
Sending this as a PR as I’m not sure why this requirement made it into Kirby back then.
As far as I can tell, the email is only used for the „Send email“ button in the Panel. We should add a check there and hide it if there is no valid email.
=> Don’t require email address for user

core/user.php
Users now don’t need to have passwords to be valid.
A user without password can’t login but there is a new $user->loginPasswordless() method for that.
Passwordless login allows the developer to log users in based on other kinds of authentication (OAuth, email, SMS etc.).
=> Support for passwordless login

core/kirbytext.php, kirby/component/markdown.php, kirby/component/smartypants.php
I did replace the Markdown parser in a project and needed the context of the current field.
This pull request updates the Kirbytext->parse() method to pass the current field to the parser. With this the parse method inside the component can base decisions on the current context the parser is in.
This closes #529 as it's no longer available.
=> Provide the field to the parser components.
